### PR TITLE
Add "Others" to legend

### PR DESCRIPTION
**Pull request by eastcirclek**
Figure out https://github.com/grafana/piechart-panel/issues/80. If you have small slices combined in your pie chart, now you also have a corresponding entry for the combined slice in your legend instead of entries for the already combined small slices.

### CODE REVIEW

**Comment by Ijin08** [comment]
Hi! This is a great and needed fix. But the threshold seem to work differently for piechart and legend. For instance when value = threshold they handle it differently: 
image

When only one value is below the threshold it keeps its name in piechart but is called other i legend:
image

**Comment by GedPL** [comment]
Using 
Elasticsearch 5.5.0
Grafana 4.6.3
Pie Chart:     "version": "1.1.6",    "updated": "2017-10-11"

Looks like Others doesn't work in legend. Or i missed something ?
Combine threshold is set to 0.1:
image

**Comment by GedPL** [comment]
When do you plan to have it merged ?
Additionally would be great to keep that one in mind:
https://github.com/grafana/piechart-panel/issues/120

Thanks !

**Comment by briangann** [comment]
a similar function was merged into v1.4.0, if it doesn't work as expected, please let us know!

**Pull request closed without merging**
