### PR TITLE
fixed legend width override for ie11

### LINKED ISSUE #143: IE 11 broken legend
In IE 11 the legend does not appear properly when set to show to the right hand side.

image

This was mostly fixed in this [Grafana Github issue](https://github.com/grafana/grafana/issues/11165) where the workaround was to manually set the width of the legend.

Could this fix also be applied to this plugin please?

### PR DESCRIPTION
**Pull request by Ijin08**
fixed panel height to get rid of dual scrolls
 + minor fixes

fixes #143

skarmavbild 2018-05-15 kl 15 57 57 2

### CODE REVIEW

**Comment by marefr** [comment]
Maybe was to quick there - @Ijin08  is it required in IE11 so set a fixed width of the legend when positioned to the right?

**Comment by Ijin08** [comment]
@marefr yes, you have to set a fixed width for the legend when it is on the right side. Same as for the graph panel.

**Comment by marefr** [comment]
*Before:*

Chrome:
image

Firefox:
image

IE11:
image

*After:*

Chrome:
image

Firefox:
image

IE11:
image

**Comment by marefr** [comment]
@Ijin08 legend to the right is working :+1: However seems like there's an issue in IE11 when legend is below the pie chart as well. See last screenshot above. Should we fix this in this issue as well or should we create a separate one just to get out the fix for dobule scrollbars?

**Comment by Ijin08** [comment]
@marefr I created the issue with legend below piechart so I fixed it in this issue.

**Pull request merged**
